endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\SvgWriter
        size: 60
        margin: 10
        encoding: 'UTF-8'
        errorCorrectionLevel: 'low'
        roundBlockSizeMode: 'margin'
        validateResult: false
