# Default configuration for extension with alias: "survos_fw"
survos_fw:
  theme: fw7
  enabled: true
  name: Voxitour
  projects:

    # Prototype
    omar:
      code: omar
      logo: logo/omar.png
      name: OmarExpo

    batsi: # previously pgsc
      code: batsi
      logo: /logos/batsi_logo.jpeg
      name: Batsi
      tabs:
        - locations
        - artists
        - obras
      #          - share
      #          - scan
      database: Batsi
      stores:
        - name: artists
          schema: ++id,name
          url: https://pgsc.survos.com/api/artists?local={locale}
        - name: locations
          schema: ++id,name
          url: https://pgsc.survos.com/api/locations?local={locale}
        - name: objects
          schema: ++id,title
          url: https://pgsc.survos.com/api/obras?local={locale}

    modo: # configuration code for database, etc.
      code: modo
      logo: /logos/modo_logo.webp
      name: El Modo
      tabs:
        - expos
        - info
        # - share
        # if data is set, composer req survos/js-twig-bundle
        #      data: # must be json-ld

        # indexDb database name
      database: Modo
      stores:
        - name: expos
          schema: code
          url: https://modo.survos.com/api/{locale}/expos
        - name: objects
          schema: ++id
          url: https://modo.survos.com/api/{locale}/objs

      members:
        # Prototype
        - email: tacman@gmail.com
          role: PROJECT_ADMIN
