# Default configuration for extension with alias: "survos_fw"
survos_fw:
  theme: fw7
  enabled: true
  name: Voxitour
  projects:

    # Prototype
#    omar:
#      code: omar
#      logo: logo/omar.png
#      name: OmarExpo

    chijal: # previously pgsc
      code: chijal
      logo: /logos/batsi_logo.jpeg
      name: Batsi
      tabs:
        - locations
        - artists
        - obras
      #          - share
      #          - scan
      database: chijal
      stores:
        - name: artists
          schema: code
          url: https://pgsc.survos.com/{locale}/api/artists
        - name: locations
          schema: code
          url: https://pgsc.survos.com/{locale}/api/locations
        - name: objects
          schema: code,artistCode,location.id
          url: https://pgsc.survos.com/{locale}/api/obras

    modo: # configuration code for database, etc.
      code: modo
      logo: /logos/modo_logo.webp
      name: El Modo
      tabs:
        - expos
        - info
        # - share
        # if data is set, composer req survos/js-twig-bundle
        #      data: # must be json-ld

        # indexDb database name
      database: Modo
      stores:
        - name: expos
          schema: code
          url: https://modo.survos.com/api/{locale}/expos
        - name: objects
          schema: ++id
          url: https://modo.survos.com/api/{locale}/objs

      members:
        # Prototype
        - email: tacman@gmail.com
          role: PROJECT_ADMIN

    cmas: # configuration code for database, etc.
      code: cmas
      name: CMAS
      tabs:
        - sacros
        - info
      database: cmas
      stores:
        - name: sacros
          schema: code
          url: https://pgsc.survos.com/{locale}/api/sacros
